### ISSUE TITLE
Questions,

### ISSUE THREAD

**Issue by juliolitwin** [dudu502/LittleBee#7]
Hey, I'm glad the project is back. :)

Now with gameplay videos it's even better!
A question related to frame sync and state, are you working with interpolation/extrapolation/predictions or is it something more like lockstep?

Thanks,
Cheers!

**Comment by dudu502** [comment]
Hi @juliolitwin 
I use the ECS to process the keyframe command and roll back frame, all this data-related logic runs on a thread,
and the main thread (unity) will read the components ( the C of ECS ) and apply them to a display. 
The display part will interpolate the current data to meet a better rendering.
Unless some key frame comes, all future behaviors will reuse the current behavior, the self role in the self device should respond in time rather than waiting for the server to return (TODO). This may be a sort of prediction.
Thanks
